apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drug-search
  name: drug-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drug-search
  strategy: {}
  template:
    metadata:
      labels:
        app: drug-search
    spec:
      containers:
      - image: weifang993/drug-search:latest
        name: drug-search
        resources: {}
status: {}
